name: "Feishu Notify"
description: "Send notifications to Feishu on pull request events"
inputs:
  webhook_url:
    description: "The Feishu webhook URL"
    required: true
  title:
    description: "The title of the notification"
    required: true
  template:
    description: "The message template"
    required: true
  content:
    description: "The content of the pull request body"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "$(jq -n --arg title "${{ inputs.title }}" \
                      --arg text "${{ inputs.template }}\n\n${{ inputs.content }}" \
                      '{title: $title, text: $text}')" \
        "${{ inputs.webhook_url }}"
      shell: bash
      env:
        PATH: $PATH:/usr/bin
