name: Notify Feishu on New Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  notify-feishu:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Feishu
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "msg_type": "text",
                "content": {
                    "text": "A new pull request has been created: ${{ github.event.pull_request.html_url }}"
                }
              }' \
          $FEISHU_WEBHOOK_URL