name: Notify Feishu on Pull Request Merged

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  notify-feishu:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Feishu
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "msg_type": "interactive",
                "card": {
                    "config": {
                        "wide_screen_mode": true
                    },
                    "header": {
                        "title": {
                            "tag": "plain_text",
                            "content": "Pull Request Merged"
                        },
                        "template": "green"
                    },
                    "elements": [
                        {
                            "tag": "div",
                            "text": {
                                "tag": "lark_md",
                                "content": "**Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})\n**Pull Request:** [#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\n**Author:** ${{ github.event.pull_request.user.login }}\n**Merged By:** ${{ github.event.pull_request.merged_by.login }}"
                            }
                        },
                        {
                            "tag": "action",
                            "actions": [
                                {
                                    "tag": "button",
                                    "text": {
                                        "tag": "plain_text",
                                        "content": "View Pull Request"
                                    },
                                    "url": "${{ github.event.pull_request.html_url }}",
                                    "type": "primary"
                                }
                            ]
                        }
                    ]
                }
              }' \
          $FEISHU_WEBHOOK_URL