name: Notify Feishu on New Pull Request or Update

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  notify-feishu:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Feishu on Pull Request Opened or Updated
        uses: ./.github/actions/feishu-notify
        with:
          webhook_url: ${{ secrets.FEISHU_WEBHOOK_URL }}
          title: ${{ github.event.action == 'opened' && 'New Pull Request' || 'Pull Request Updated' }}
          template: "blue"
          content: |
            **Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})
            **Pull Request:** [#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            **Author:** ${{ github.event.pull_request.user.login }}
            **Description:** ${{ github.event.pull_request.body || 'No description provided.' }}